version: '3.4'

services:

  ticktock-dev:
    image: ticktock-dev
    build:
      context: .
      target: development
    ports:
      - "8000:80"
    entrypoint: nodemon start.js
    volumes:
      - .:/opt/ticktock
      - ./example/notifications:/opt/ticktock/notifications
      - ./example/config.yml:/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      
  ticktock-prod:
    image: tkambler/ticktock
    build:
      context: .
      target: production
    ports:
      - "8000:80"
    volumes:
      - ./example/config.yml:/config.yml
      - /var/run/docker.sock:/var/run/docker.sock

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"